version: '3'

networks:
  rede_a:

services:
  zipkin:
    image: openzipkin/zipkin-slim:latest
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - rede_a

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
    networks:
      - rede_a

  service_a:
    build:
      context: .
      dockerfile: Dockerfile.service_a
    environment:
      - HTTP_PORT=:8080
    ports:
      - "8080:8080"
    networks:
      - rede_a

  service_b:
    build:
      context: .
      dockerfile: Dockerfile.service_b
    ports:
      - "8181:8181"
    environment:
      - HTTP_PORT=:8181
      - WEATHER_API_KEY=
      - OTEL_COLLECTOR_ENDPOINT=otel-collector:4317
      - TELEMETRY_SERVICE_NAME=TEMPERATURA_POR_CEP_E_TELEMETRIA
    depends_on:
      - zipkin
      - otel-collector
      - service_a
    networks:
      - rede_a
    